-- Your SQL goes here
CREATE TABLE frames (
	id INTEGER NOT NULL PRIMARY KEY,
	project INTEGER NOT NULL,
	start DATETIME NOT NULL,
	end DATETIME,
	FOREIGN KEY(project) REFERENCES projects(id)
);

CREATE TABLE projects (
	id INTEGER NOT NULL PRIMARY KEY,
	name VARCHAR NOT NULL UNIQUE,
	archived BOOLEAN NOT NULL DEFAULT 0,
	last_access_time DATETIME NOT NULL DEFAULT (DATETIME('now', 'localtime'))
);
